/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab15.gabriel.group2.a2;


import static org.junit.Assert.*;
import org.junit.jupiter.api.Test;

 public class AppTest {
  @Test
  public void AppTest(){
    App appTest = new App();
   }
 }